# Generated by Django 5.0.6 on 2024-05-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='user',
        ),
    ]
